apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.application.name }}
  labels: {{ toYaml .Values.application.labels | nindent 4 }}
automountServiceAccountToken: {{ default false .automountServiceAccountToken }}
