{{- if and .Values.application .Values.configmap.IPAM_DATABASE_PASS }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
  labels: {{ toYaml .Values.application.labels | nindent 4 }}
type: "Opaque"
data:
  IPAM_DATABASE_PASS: {{ .Values.configmap.IPAM_DATABASE_PASS | b64enc }}
{{- end }}
