apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
  labels: {{ toYaml .Values.application.labels | nindent 4 }}
spec:
  gateways:
  -  {{ .Values.application.name }}
  hosts:
  - {{ printf "%s.%s" .Values.application.name .Values.application.domain }}
  http:
  - route:
    - destination:
        host: {{ .Values.application.name }}
        port:
          number: {{ .Values.application.ports.port }}